---
title: "Estimating dose-specific cell division and apoptosis rates from chemo-sensitivity experiments"
author: "Yiyi Liu, Forrest Crawford"
date: "April 5, 2017"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

In this vignette, we give an example illustrating the usage of R package bdChemo.

```{r}
library("bdChemo")
data(example)
bd.example = bdChemo(x0, xtc, z, xt, bk,
Niter = c(1,2,3,10,15,20,30,40,80) * 100,
Nburn = 5000, thin = 10, sa2l = .5, sa2m = 1, at = 10, bt = 1, al = 25, bl = 6,
ql = .025, qu = .975, plot.name = "example", sample.return = F)
## We set the number of iterations small here for illustration purpose
## We suggest increasing it to the scale of 1e7 in real data analysis
```

The above call will produce a pdf file "example.pdf" with cell growth, birth and death rate curves as shown in Figure 3 of the manuscript. In addition, it also return a list "bd.example" with elements as described in users' manual. We will show the usage of these elements in the following code.

```{r}
## log concentrations where mu and lambda are returned
znew = bd.example$znew

## means and credible intervals of mu, lambda and Kendall Process at znew
lambda.mean = bd.example$lambdas[1,]
lambda.lower.bound = bd.example$lambdas[2,]
lambda.upper.bound = bd.example$lambdas[3,]
mu.mean = bd.example$mus[1,]
mu.lower.bound = bd.example$mus[2,]
mu.upper.bound = bd.example$mus[3,]
kmean.mean = bd.example$kmean[1,]
kmean.lower.bound = bd.example$kmean[2,]
kmean.upper.bound = bd.example$kmean[3,]

## means and credible intervals of GI50, TGI, LC50 and IC50
gi50.mean = bd.example$summary[1,1]
gi50.lower.bound = bd.example$summary[2,1]
gi50.upper.bound = bd.example$summary[3,1]

tgi.mean = bd.example$summary[1,2]
tgi.lower.bound = bd.example$summary[2,2]
tgi.upper.bound = bd.example$summary[3,2]

lc50.mean = bd.example$summary[1,3]
lc50.lower.bound = bd.example$summary[2,3]
lc50.upper.bound = bd.example$summary[3,3]

ic50.mean = bd.example$summary[1,4]
ic50.lower.bound = bd.example$summary[2,4]
ic50.upper.bound = bd.example$summary[3,4]

## posterior samples of mu and lambda (can be used to calculate other summary statistics of interest)
lambda.sample = bd.example$post.lambda
mu.sample = bd.example$post.mu
```
